In [3]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('abalone.csv')

In [58]:
data.head()

Sex  Length  Diameter  Height  WholeWeight  ShuckedWeight  VisceraWeight  \
0    1   0.455     0.365   0.095       0.5140         0.2245         0.1010   
1    1   0.350     0.265   0.090       0.2255         0.0995         0.0485   
2   -1   0.530     0.420   0.135       0.6770         0.2565         0.1415   
3    1   0.440     0.365   0.125       0.5160         0.2155         0.1140   
4    0   0.330     0.255   0.080       0.2050         0.0895         0.0395   

   ShellWeight  
0        0.150  
1        0.070  
2        0.210  
3        0.155  
4        0.055

In [59]:
data.to_numpy()[0]

array([1.    , 0.455 , 0.365 , 0.095 , 0.514 , 0.2245, 0.101 , 0.15  ])

In [8]:
data['Sex'] = data['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))

Разделите содержимое файлов на признаки и целевую переменную. В последнем столбце записана целевая переменная, в остальных — признаки.

Обучите случайный лес (sklearn.ensemble.RandomForestRegressor) с различным числом деревьев: от 1 до 50 (не забудьте выставить "random_state=1" в конструкторе). Для каждого из вариантов оцените качество работы полученного леса на кросс-валидации по 5 блокам. Используйте параметры "random_state=1" и "shuffle=True" при создании генератора кросс-валидации sklearn.cross_validation.KFold.  В качестве меры качества воспользуйтесь коэффициентом детерминации (sklearn.metrics.r2_score).

Определите, при каком минимальном количестве деревьев случайный лес показывает качество на кросс-валидации выше 0.52. Это количество и будет ответом на задание.

Обратите внимание на изменение качества по мере роста числа деревьев. Ухудшается ли оно?

In [11]:
y = data.Rings
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [15]:
data.drop(['Rings'], axis=1, inplace= True)

In [18]:
data

Sex  Length  Diameter  Height  WholeWeight  ShuckedWeight  \
0       1   0.455     0.365   0.095       0.5140         0.2245   
1       1   0.350     0.265   0.090       0.2255         0.0995   
2      -1   0.530     0.420   0.135       0.6770         0.2565   
3       1   0.440     0.365   0.125       0.5160         0.2155   
4       0   0.330     0.255   0.080       0.2050         0.0895   
...   ...     ...       ...     ...          ...            ...   
4172   -1   0.565     0.450   0.165       0.8870         0.3700   
4173    1   0.590     0.440   0.135       0.9660         0.4390   
4174    1   0.600     0.475   0.205       1.1760         0.5255   
4175   -1   0.625     0.485   0.150       1.0945         0.5310   
4176    1   0.710     0.555   0.195       1.9485         0.9455   

      VisceraWeight  ShellWeight  
0            0.1010       0.1500  
1            0.0485       0.0700  
2            0.1415       0.2100  
3            0.1140       0.1550  
4            0.0395       0.0550  
...             ...          ...  
4172         0.2390       0.2490  
4173         0.2145       0.2605  
4174         0.2875       0.3080  
4175         0.2610       0.2960  
4176         0.3765       0.4950  

[4177 rows x 8 columns]

In [63]:
for i in range(1,51):
    print(cross_val_score(RandomForestClassifier(n_estimators= i,random_state=1), data, y, cv=5,scoring='r2'))


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.01529966 0.03840055 0.0569987  0.07896752 0.16061214]
[0.14436395 0.1741462  0.20611472 0.23258792 0.22686116]
[0.12530523 0.1516187  0.16866069 0.14117458 0.16844051]
[0.07013527 0.13222646 0.165277   0.11162335 0.17603519]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.08128071 0.17066257 0.21358219 0.17084079 0.1786057 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.14035159 0.16799178 0.24986942 0.20660123 0.2309506 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.17913775 0.24370279 0.30797566 0.23454267 0.23048324]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.20310046 0.23104558 0.32197716 0.24178674 0.29275965]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.19518719 0.25217963 0.33457852 0.30663847 0.27628502]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.1728963  0.24567685 0.31275951 0.27961692 0.28645022]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.1917321  0.26634642 0.2729719  0.26892328 0.30981847]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.19552156 0.27819078 0.29969144 0.29709469 0.30853322]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.215249   0.27412654 0.30610879 0.30801829 0.31869841]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.21814682 0.28887392 0.26597115 0.30399381 0.3243068 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.22817772 0.30118277 0.29350744 0.31388254 0.35234871]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.26306297 0.31558179 0.29560766 0.31664219 0.36485072]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.24110644 0.3018795  0.30669219 0.29353014 0.33715934]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.24099498 0.30780168 0.30949249 0.31434248 0.33190148]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25559552 0.32231682 0.31766003 0.31250272 0.34276772]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.28925477 0.31918155 0.31544313 0.32779577 0.33797723]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.29293277 0.31720749 0.33212825 0.34561849 0.36742123]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.28100714 0.30211174 0.34554636 0.35688706 0.35982655]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.2786666  0.31442058 0.36573186 0.33205023 0.35795709]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.26941588 0.29154471 0.38300039 0.35056286 0.35012872]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.2972795  0.29630568 0.39070121 0.34676835 0.34545507]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.30017731 0.2986281  0.36549851 0.34251389 0.34370245]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.29248695 0.28899005 0.35056357 0.35113779 0.36695387]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27041897 0.28155829 0.35791436 0.33963926 0.3571392 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27588024 0.29131247 0.34437957 0.34665336 0.39067265]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.26707533 0.29293817 0.33889565 0.36079656 0.39546314]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25749025 0.29398326 0.34286274 0.34619342 0.40399256]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27978114 0.28713211 0.34893006 0.3479182  0.40130521]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27599169 0.3040858  0.3307281  0.34550351 0.40177257]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.28134151 0.31349161 0.33154486 0.34688333 0.40048732]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27309388 0.30060216 0.35161368 0.35355248 0.39184106]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.29583059 0.30896289 0.35359723 0.35136776 0.4001368 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.2811186  0.29189308 0.34694651 0.35665709 0.39663156]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27041897 0.29572507 0.34624644 0.35286257 0.3987347 ]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.27721769 0.30176338 0.3346952  0.36263632 0.39452841]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25671007 0.31186592 0.33656206 0.35309254 0.37945589]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25024571 0.32800676 0.3318949  0.36229137 0.37034227]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25916206 0.34066397 0.35126364 0.3581519  0.38868635]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.25046862 0.33659973 0.34216267 0.35596717 0.37606749]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.28256751 0.33218712 0.3425127  0.34492858 0.38646636]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.30920513 0.33961888 0.34776327 0.35125278 0.39102317]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.30920513 0.32858737 0.35698092 0.35769195 0.39721576]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.32168803 0.32347803 0.36503179 0.3565421  0.40819884]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.33015857 0.33160652 0.36841549 0.35838187 0.40773148]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.31968185 0.34867633 0.35943119 0.35435738 0.41497564]


C:\Users\ostap\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[0.31555803 0.34588942 0.34449625 0.3471133  0.42443978]


In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

from sklearn.metrics import fbeta_score, make_scorer

two_scorer = make_scorer(r2_score)



kf = KFold(random_state=1, shuffle=True, n_splits=5)
parameters = {'n_estimators':range(1,51)}
clf = GridSearchCV(RandomForestClassifier(random_state=1), parameters,cv = kf,scoring=two_scorer)
clf.fit(data,y)
print(clf.score)

<bound method BaseSearchCV.score of GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=RandomForestClassifier(random_state=1),
             param_grid={'n_estimators': range(1, 51)},
             scoring=make_scorer(r2_score))>


In [38]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [53]:
clf.scorer_

make_scorer(r2_score)

In [ ]:
best_params = grid.best_params_
model = grid.best_estimator_
score = grid.best_score_
for item in grid.grid_scores_:
    print "\t%s %s %s" % ('\tGRIDSCORES\t',  "R" , item)
print '%s\tHP\t%s\t%f' % ("R" , str(best_params) ,abs(score))

In [52]:
clf.best_score_

0.354310566207344